# Example Ansible Operator

Init and simple deployment:
```
operator-sdk init --domain bszeti.github.com --plugins ansible
operator-sdk create api --group cache --version v1alpha1 --kind Memcached --generate-role
make docker-build docker-push IMG="quay.io/bszeti/memcached-operator:v0.0.1"

make deploy IMG="quay.io/bszeti/memcached-operator:v0.0.1"
kubectl apply -f config/samples/cache_v1alpha1_memcached.yaml

make undeploy

```

## Resources created:

`oc kustomize config/default`

* namespace/bszeti-operator-system
* customresourcedefinition.apiextensions.k8s.io/memcacheds.cache.bszeti.github.com
* serviceaccount/bszeti-operator-controller-manager
* role.rbac.authorization.k8s.io/bszeti-operator-leader-election-role
* clusterrole.rbac.authorization.k8s.io/bszeti-operator-manager-role
* rolebinding.rbac.authorization.k8s.io/bszeti-operator-leader-election-rolebinding
* clusterrolebinding.rbac.authorization.k8s.io/bszeti-operator-manager-rolebinding
* configmap/bszeti-operator-manager-config
* deployment.apps/bszeti-operator-controller-manager

## Deployment Namespace

The default generated deployment creates a new namespace when `make deploy` is run.

### Deploy in a new namespace

* `config/default/kustomization.yaml`: Set `namespace` - should start with `namePrefix` to create a new Namespace correctly.
* `config/default/kustomization.yaml`: Set `namePrefix` to anyting

### Deploy in existing namespace

* `config/manager/manager.yaml`: Remove `Namespace`
* `config/default/kustomization.yaml`: Set `namespace` to existing namespace
* `config/default/kustomization.yaml`: Set `namePrefix` to anyting

[NOTE]
By default a `ClusterRole` is created for the operator and all namespaces are monitored, so have only one operator deployment in the cluster.

## Notes

### Set image url

* `Makefile`: Set `IMAGE_TAG_BASE` and `VERSION`
* `Makefile`: Change `IMG ?= $(IMAGE_TAG_BASE):$(VERSION)`

Then simply `make docker-build docker-push` and `make deploy` can be used.

[NOTE]
Add `imagePullPolicy: Always` in `config/manager/manager.yaml` to avoid caching, if version is not `latest`.

## Watch self namespace only

By default the operator monitors all namespaces. The Deployment can be changed to operate within the self namespace only:

* `config/rbac/kustomization.yaml`: Use _Role_ (`config/rbac/role*.yaml`) instead of _ClusterRole_ (`config/rbac/clusterrole*.yaml`)
* `config/manager/manager.yaml` Add _WATCH_NAMESPACE_ env var for operator Deployment:
+
```
env:
  - name: WATCH_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
```


## Manifest templates in files

Must use _lookup_:
`definition: "{{ lookup('template','file-name.yaml.j2') | from_yaml }}"`

Path searched for file:
```
operator-root/roles/memcached/templates/file-name.yaml.j2
operator-root/roles/memcached/file-name.yaml.j2
operator-root/roles/memcached/tasks/templates/file-name.yaml.j2
operator-root/roles/memcached/tasks/file-name.yaml.j2
```

Doesn't work without lookup. Tried:

* `src: 'templates/file-name.yaml.j2'`
+
Doesn't use it as Jinja template

* `template: 'templates/file-name.yaml.j2'`
+
Works only in local run, not in container.


## Molecule tests

For the generated `default` molecule test:

* Use _kustomize_ version 3.5.4. It's expected on the path: `cp bin/kustomize /usr/local/bin/kustomize` or set `export KUSTOMIZE_PATH=/absolute_path/bin/kustomize`
* Install _yamllint_: `brew install yamllint`
* Error `ModuleNotFoundError: No module named 'openshift'`: `pip install openshift`
* Install required pacakges: `ansible-galaxy collection install -r requirements.yml` 
* Set `export OPERATOR_IMAGE=quay.io/bszeti/memcached-operator:v0.0.1` (this sets `newName: quay.io/bszeti/memcached-operator` and `newTag: v0.0.1` in `config/testing/kustomization.yaml`)

Run test:
```
mulecule converge
molecule destroy
# or
molecule test
```
Tests are run in an `osdk-test` namespace in the currently logged in cluster, set `export TEST_OPERATOR_NAMESPACE=my-osdk-test` to use another namespace.

In case of errors the operator Pod log and the resources in the namespace are collected. To decrease the verbosity:

* Comment out `Output gathered resources` and `Output gathered logs` steps in `molecule/default/verify.yml` to completely disable these steps.
* Or just decrease pod log level, by removing `- debug_logs_patch.yaml` in `config/testing/kustomization.yaml`.
* Or collect less manifests, e.g. remove `Secret` under `Retrieve relevant resources` in `molecule/default/verify.yml`

[NOTE]
====
The `molecule test` deletes and recreates the CRD which can be inconvinient on a shared development cluster. Remove `../crd` from `resources` in `config/testing/kustomization.yaml` to avoid the test touching the CRD.
Alternatively we can skip deleteing the CRD in `molecule/default/kustomize.yml`:

```
when: not (item.kind == 'CustomResourceDefinition' and state == 'absent')
```
====

### Local testing

Local testing can be performed with a temporary Kubernets cluster using https://kind.sigs.k8s.io/[kind]:

* Install _kind_: `brew install kind`
* Install `docker` python module: `pip install docker`
* Run test: `molecule test -s kind`

Run ansible-operator locally:
```
export WATCH_NAMESPACE=bszeti
ansible-operator run 2>&1 | grep '^{' | jq  .
# or 
make run 2>&1 | grep '^{' | jq  .
```

[NOTE]
On Mac, socket files are left behind causing unnecessary error logs. Add delete step to `run` command: `rm $(wildcard /tmp/ansibleoperator-*) 2>/dev/null || true`

## PostgreSQL database

Image: docker hub postgres:11
Image: registry.redhat.io/rhel8/postgresql-12:1
Env vars:
 - POSTGRESQL_USER=dbuser
 - POSTGRESQL_PASSWORD=secret
 - POSTGRESQL_DATABASE=db
 - POSTGRESQL_ADMIN_PASSWORD
resources:
volume: /var/lib/pgsql/data
size: 

Secret: [postgresql-]
apiVersion: v1
kind: Secret
  metadata:
    labels:
      pg-cluster: ${your-cluster-name}
    name: ${your-cluster-name}-${your-custom-user}-secret
type: Opaque
stringData:
  username: ${your-custom-user}
  password: SECRET

Certificate-Based Authentication?

Common labels for all resources.

- name: POSTGRESQL_DATABASE
            #   value

## TODO

*Adhoc idempotency errors?*
```
CRITICAL Idempotence test failed because of the following tasks:
*  => (item={'apiVersion': 'apps/v1', 'kind': 'Deployment', 'metadata': {'labels': {'control-plane': 'controller-manager'}, 'name': 'osdk-controller-manager', 'namespace': 'my-osdk-test'}, 'spec': {'replicas': 1, 'selector': {'matchLabels': {'control-plane': 'controller-manager'}}, 'template': {'metadata': {'labels': {'control-plane': 'controller-manager'}}, 'spec': {'containers': [{'args': ['--secure-listen-address=0.0.0.0:8443', '--upstream=http://127.0.0.1:8080/', '--logtostderr=true', '--v=10'], 'image': 'gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0', 'name': 'kube-rbac-proxy', 'ports': [{'containerPort': 8443, 'name': 'https'}]}, {'args': ['--health-probe-bind-address=:6789', '--metrics-bind-address=127.0.0.1:8080', '--leader-elect', '--leader-election-id=memcached-operator'], 'env': [{'name': 'ANSIBLE_GATHERING', 'value': 'explicit'}, {'name': 'WATCH_NAMESPACE', 'valueFrom': {'fieldRef': {'fieldPath': 'metadata.namespace'}}}], 'image': 'quay.io/bszeti/memcached-operator:v0.0.1', 'imagePullPolicy': 'Always', 'livenessProbe': {'httpGet': {'path': '/healthz', 'port': 6789}, 'initialDelaySeconds': 15, 'periodSeconds': 20}, 'name': 'manager', 'readinessProbe': {'httpGet': {'path': '/readyz', 'port': 6789}, 'initialDelaySeconds': 5, 'periodSeconds': 10}, 'securityContext': {'allowPrivilegeEscalation': False}}] => Set resources to present
WARNING  An error occurred during the test sequence action: 'idempotence'. Cleaning up.
```