# Example Ansible Operator

## Templating 

### Manifest templates in files

Must use _lookup_:

  definition: "{{ lookup('template','file-name.yaml.j2') | from_yaml }}"

For a template with multiple manifests:

  definition: "{{ lookup('template','file-name.yaml.j2') | from_yaml_all | list }}"

Path searched for file:
```
/roles/memcached/templates/file-name.yaml.j2
/roles/memcached/file-name.yaml.j2
/roles/memcached/tasks/templates/file-name.yaml.j2
/roles/memcached/tasks/file-name.yaml.j2
```

[NOTE]
====
Doesn't work without lookup. Tried:

* `src: 'templates/file-name.yaml.j2'`
+
Doesn't use it as Jinja template

* `template: 'templates/file-name.yaml.j2'`
+
Works only in local run, not in container.
====

For Debugging use:
```
- name: show templating yaml string
  debug:
    msg: "{{ lookup('template','file-name.yaml.j2') }}"
- name: show templating json
  debug:
    msg: "{{ lookup('template','file-name.yaml.j2') | from_yaml }}"
```

### Jinja blocks

Removing new line after block (_trim_blocks_) is enabled by default. To keep the identation of yaml files with Jinja blocks, we have too options:

* Start every `{%` at the beginning of the line, so we have no whitespaces added
* Add `#jinja2: lstrip_blocks: True` to the top of the file.

[NOTE]
Using `{%-` doesn't work as it removes the previous line break too and we end up with no line breaks between lines.

## Molecule tests

For the generated `default` molecule test:

* Use _kustomize_ version 3.5.4. It's expected on the path: `cp bin/kustomize /usr/local/bin/kustomize` or set `export KUSTOMIZE_PATH=/absolute_path/bin/kustomize`
* Install _yamllint_: `brew install yamllint`
* Error `ModuleNotFoundError: No module named 'openshift'`: `pip install openshift`
* Install required pacakges: `ansible-galaxy collection install -r requirements.yml` 
* Set `export OPERATOR_IMAGE=quay.io/bszeti/memcached-operator:v0.0.1` (this sets `newName: quay.io/bszeti/memcached-operator` and `newTag: v0.0.1` in `config/testing/kustomization.yaml`)

Run test:
```
mulecule converge
molecule verify
molecule destroy
# or
molecule test
```
Tests are run in an `osdk-test` namespace in the currently logged in cluster, set `export TEST_OPERATOR_NAMESPACE=my-osdk-test` to use another namespace.

In case of errors the operator Pod log and the resources in the namespace are collected. To decrease the verbosity:

* Comment out `Output gathered resources` and `Output gathered logs` steps in `molecule/default/verify.yml` to completely disable these steps.
* Or just decrease pod log level, by removing `- debug_logs_patch.yaml` in `config/testing/kustomization.yaml`.
* Or collect less manifests, e.g. remove `Secret` under `Retrieve relevant resources` in `molecule/default/verify.yml`

[NOTE]
====
The `molecule test` deletes and recreates the CRD which can be inconvinient on a shared development cluster. Remove `../crd` from `resources` in `config/testing/kustomization.yaml` to avoid the test touching the CRD.
Alternatively we can skip deleteing the CRD in `molecule/default/kustomize.yml`:

```
when: not (item.kind == 'CustomResourceDefinition' and state == 'absent')
```
====

### Local testing

Local testing can be performed with a temporary Kubernets cluster using https://kind.sigs.k8s.io/[kind]:

* Install _kind_: `brew install kind`
* Install `docker` python module: `pip install docker`
* Run test: `molecule test -s kind`

Run ansible-operator locally:
```
export WATCH_NAMESPACE=bszeti
ansible-operator run --ansible-verbosity 7 2>&1 | grep '^{' | jq  .
# or 
make run 2>&1 | grep '^{' | jq  .
```

[NOTE]
On Mac, socket files are left behind causing unnecessary error logs. Add delete step to `run` command: `rm $(wildcard /tmp/ansibleoperator-*) 2>/dev/null || true`

## TODO

*Adhoc idempotency errors?*
```
CRITICAL Idempotence test failed because of the following tasks:
*  => (item={'apiVersion': 'apps/v1', 'kind': 'Deployment', 'metadata': {'labels': {'control-plane': 'controller-manager'}, 'name': 'osdk-controller-manager', 'namespace': 'my-osdk-test'}, 'spec': {'replicas': 1, 'selector': {'matchLabels': {'control-plane': 'controller-manager'}}, 'template': {'metadata': {'labels': {'control-plane': 'controller-manager'}}, 'spec': {'containers': [{'args': ['--secure-listen-address=0.0.0.0:8443', '--upstream=http://127.0.0.1:8080/', '--logtostderr=true', '--v=10'], 'image': 'gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0', 'name': 'kube-rbac-proxy', 'ports': [{'containerPort': 8443, 'name': 'https'}]}, {'args': ['--health-probe-bind-address=:6789', '--metrics-bind-address=127.0.0.1:8080', '--leader-elect', '--leader-election-id=memcached-operator'], 'env': [{'name': 'ANSIBLE_GATHERING', 'value': 'explicit'}, {'name': 'WATCH_NAMESPACE', 'valueFrom': {'fieldRef': {'fieldPath': 'metadata.namespace'}}}], 'image': 'quay.io/bszeti/memcached-operator:v0.0.1', 'imagePullPolicy': 'Always', 'livenessProbe': {'httpGet': {'path': '/healthz', 'port': 6789}, 'initialDelaySeconds': 15, 'periodSeconds': 20}, 'name': 'manager', 'readinessProbe': {'httpGet': {'path': '/readyz', 'port': 6789}, 'initialDelaySeconds': 5, 'periodSeconds': 10}, 'securityContext': {'allowPrivilegeEscalation': False}}] => Set resources to present
WARNING  An error occurred during the test sequence action: 'idempotence'. Cleaning up.
```

https://stackoverflow.com/questions/45428447/how-to-disable-molecule-idempotence-check-on-ansible-role-test

*yamllint template errors*

`yamllint` shows errors due to j2 syntax. We need to skip scheking either by renaming files to `*.yaml.j2` or excluding path by adding `ignore: '**/templates/**'` in `molecule/default/molecule.yml`.

https://github.com/adrienverge/yamllint/issues/69
