---
# vars file for Memcached
values:
  replicas:  "{{ replicas |  default(default_values.replicas) }}"
  foo:       "{{ foo | default(default_values.foo) }}"
  resources: "{{ default_values.resources | combine(resources | default({}), recursive=True) }}"
  database:  "{{ default_values.database | combine(database | default({}), recursive=True) }}"

common_labels:
  instance_name: "{{ ansible_operator_meta.name }}"
  mylabel: "hello"