apiVersion: cache.bszeti.github.com/v1alpha1
kind: Memcached
metadata:
  name: test2
  annotations:
    ansible.sdk.operatorframework.io/reconcile-period: 60s
spec:
  size: 2
  fooValue: 'Hello World!'
