# Operator Lifecycle Manager bundle

Docs:

* Operator SDK docs: https://sdk.operatorframework.io/docs/olm-integration/
* OLM GitHub: https://github.com/operator-framework/operator-lifecycle-manager
* OLM doc: https://olm.operatorframework.io/docs/

On the top of the operator container image OLM integration requires two other images to be created:

* Bundle: An installation package for the operator. It contains the required yaml files and meta information to install the Operator.
* Catalog: An index of available bundle versions. It can be used in a _CatalogSource_ resource to make a set of Operators available on a K8s cluster.

The `Makefile` contains commands to create the required resources:

* `make bundle`: Generate manifest files required for a bundle.
* `make bundle-build bundle-push`: Build and push the bundle container image.
* `make catalog-build catalog-push`: Build and push the catalog container image.


## Bundle

OLM is expecting semantic versioning for the images, so make sure that the `VERSION` _make_ parameter is set accoringly like `0.1.2`.

First we need to generate the required filed for the bundle:

```
$ make bundle
  ...
  Display name for the operator (required):
  > BSzeti Memcached
  Description for the operator (required):
  > My Test Operator
  Provider's name for the operator (required):
  > myprovider
  Any relevant URL for the provider name (optional):
  > https://medium.com/@bszeti
  Comma-separated list of keywords for your operator (required):
  > memcached,example
  Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
  > bszeti:me@mycompany.com
  ...
  INFO[0000] Creating bundle/metadata/annotations.yaml
  INFO[0000] Creating bundle.Dockerfile
  INFO[0000] Bundle metadata generated suceessfully
  operator-sdk bundle validate ./bundle
  INFO[0000] Found annotations file                        bundle-dir=bundle container-tool=docker
  INFO[0000] Could not find optional dependencies file     bundle-dir=bundle container-tool=docker
  INFO[0000] All validation tests have completed successfully
```

The tasks runs a couple of steps:

* Creates `config/manifests` directory to record the answers and a _kustomize_ script to collects the required manifests for the deployment of the operator.
* Operator image url can be set in `IMG` parameter
* Create `bundle` directory to contain the resources required in the bundle image (using the `config/manifests` dir to get CRD, SA, roles, etc...). Note `bundle/manifests/memcached-operator.clusterserviceversion.yaml` with the `ClusterServiceVersion` that describes the operator's metadata and also contains the _permissions_ and _deployment_ of the operator.
* Generate `bundle.Dockerfile` for the docker build

[NOTE]
====
Modify the generated content in `config/manifests` according to what is needed for the operator installation. The `make bundle` command overwrites the files under the `bundle` directory.
====

Build and push the bundle image to an image registry:
```
$ make bundle-build bundle-push BUNDLE_IMG=quay.io/bszeti/memcached-operator-bundle:v0.0.1
```

For testing purpuses the bundle can be installed directly on a K8s cluster without building a Catalog image using `operator-sdk run bundle...`. This creates a temporary Pod in the current namespace that acts as a catalog image (serving a catalog index having the bundle). It also installs the Operator using the bundle automatically, so the a Pod of our operator image should be running.

```
$ operator-sdk run bundle quay.io/bszeti/memcached-operator-bundle:v0.0.1
  INFO[0014] Successfully created registry pod: quay-io-bszeti-memcached-operator-bundle-v0-0-1
  INFO[0014] Created CatalogSource: memcached-operator-catalog
  INFO[0014] OperatorGroup "operator-sdk-og" created
  INFO[0015] Created Subscription: memcached-operator-v0-0-1-sub
  INFO[0019] Approved InstallPlan install-zghhn for the Subscription: memcached-operator-v0-0-1-sub
  INFO[0019] Waiting for ClusterServiceVersion "default/memcached-operator.v0.0.1" to reach 'Succeeded' phase
  INFO[0019]   Waiting for ClusterServiceVersion "default/memcached-operator.v0.0.1" to appear
  INFO[0030]   Found ClusterServiceVersion "default/memcached-operator.v0.0.1" phase: Pending
  INFO[0032]   Found ClusterServiceVersion "default/memcached-operator.v0.0.1" phase: Installing
  INFO[0063]   Found ClusterServiceVersion "default/memcached-operator.v0.0.1" phase: Succeeded
  INFO[0063] OLM has successfully installed "memcached-operator.v0.0.1"

# Verify that new temporary CatalogSource is created in the current namespace
$ oc get CatalogSource
  NAME                         DISPLAY               TYPE   PUBLISHER      AGE
  memcached-operator-catalog   memcached-operator    grpc   operator-sdk   1m

# Verify the test catalog and operatro is running
oc get pods
NAME                                                              READY   STATUS      RESTARTS   AGE
ac095a4638d1696a13777bac081eaa9a0acb339453c13aed762ffabf12ntg89   0/1     Completed   0          1m   -> Job to create test catalog
quay-io-bszeti-memcached-operator-bundle-v0-0-1                   1/1     Running     0          1m   -> Test catalog
bszeti-operator-controller-manager-bb7984f77-gs7lc                1/1     Running     0          1m   -> Operator

# Cleanup this test bundle deployment
$ operator-sdk cleanup memcached-operator
  INFO[0002] subscription "memcached-operator-v0-0-1-sub" deleted
  INFO[0002] clusterserviceversion "memcached-operator.v0.0.1" deleted
  INFO[0002] catalogsource "memcached-operator-catalog" deleted
  INFO[0002] operatorgroup "operator-sdk-og" deleted
  INFO[0002] Operator "memcached-operator" uninstalled
```

## Operator Catalog
