# Adds namespace to all resources.
namespace: sforeman-test

namePrefix: my-osdk-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue


patchesStrategicMerge:
- manager_image.yaml
- debug_logs_patch.yaml
- ../default/manager_auth_proxy_patch.yaml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
images:
- name: testing
  newName: image-registry.openshift-image-registry.svc:5000/sforeman/memcached-operator
  newTag: v0.0.1
