---
# defaults file for Memcached
default_values:
  replicas: 1
  foo: default message
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 512Mi
  database:
    create_instance: False
    admin_secret:
      name: postgresql-postgres-secret
