---
- name: start memcached
  community.kubernetes.k8s:
    definition: "{{ lookup('template','memcached-deployment.yaml.j2') | from_yaml }}"

- name: create configmap
  community.kubernetes.k8s:
    # definition: "{{ lookup('template','memcached-configmap.yaml.j2') | from_yaml }}"
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-configmap'
        namespace: '{{ ansible_operator_meta.namespace }}'
      data:
        foo: '{{ foo_value }}'
